name: Workflow de Integração Continua.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  testes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x   # ou 22.x se precisar

      - run: npm ci            # mais seguro que npm install no CI
      - run: npm test
